### ISSUE TITLE
No build system for GNU/Linux

### ISSUE THREAD

**Issue by rekado** [dnet/SimpleDSO#1]
The setup.py seems to only handle the case for building on Windows.  I'd like to package SimpleDSO for GNU Guix, but I cannot see clearly how this is supposed to be built.  Is it enough to just set PYTHONPATH such that the Python dependencies can be found at runtime, and then run simpleDSO.py from the checkout?

It would be nice if a proper build system could be added.  (I'm not familiar with building Python stuff the conventional way, so I cannot provide a working patch to `setup.py`.)

**Comment by dnet** [comment]
Thanks for packaging SimpleDSO, but unfortunately I'm not a developer nor a maintainer of the project. As the repository descriptions states, this is a "Non-official mirror of the SimpleDSO project", the original one is the one on SourceForge: https://sourceforge.net/projects/simpledso/ The e-mail address of the developer is zmatkar at k25 dot cz, try contacting him directly. If you could add such a build system, send me a pull request, and I'd merge it.

**Comment by rekado** [comment]
oh, too bad.  I saw that you had already made a couple of improvements to the repository (like removing build artifacts), so I assumed you wanted to continue development.

I'll contact the original developer directly then.  Thanks!

**Comment by dnet** [comment]
> you had already made a couple of improvements to the repository (like removing build artifacts)

I did? :confused:

**Comment by rekado** [comment]
Heh, no, I misunderstood.  There have been additional commits since the latest release, but these were done by Tomas.  Never mind :)
